baseURL = "http://example.org/"
languageCode = "en-us"
title = "Chef Habitat Builder on-prem documentation"
Paginate = 4
theme = "chef"
enableGitInfo = true

# To develop against a local copy of the chef hugo theme, uncomment this line
# and set the value to the parent directory of where you have checked out the
# chef-hugo-theme repository
# themesDir = "../../../hugo-themes"

pygmentsStyle = "emacs"
pygmentsCodefences = true

[[menu.docs]]
name = "Getting started"
weight = 10
identifier = "getting-started"
url = "/docs/getting-started"

[[menu.docs]]
name = "Automate + Builder"
weight = 20
identifier = "builder-automate"
url = "/docs/builder-automate"

[[menu.docs]]
name = "Automate + OAuth"
weight = 30
identifier = "builder-oauth"
url = "/docs/builder-oauth"

[[menu.docs]]
name = "Packages"
weight = 40
identifier = "packages"
url = "/docs/packages"

[[menu.docs]]
name = "Example builder.env"
weight = 50
identifier = "builder-example"
url = "/docs/builder-example"

[[menu.docs]]
name = "Postgres"
weight = 60
identifier = "postgres"
url = "/docs/postgres"

[[menu.docs]]
name = "Minio"
weight = 70
identifier = "minio"
url = "/docs/minio"

[[menu.docs]]
name = "Artifactory"
weight = 80
identifier = "artifactory"
url = "/docs/artifactory"

[[menu.docs]]
name = "Troubleshooting"
weight = 90
identifier = "troubleshooting"
url = "/docs/troubleshooting"
