baseURL = "https://habitat.on-prem.cov/"
languageCode = "en-us"
title = "Chef Habitat Builder on-prem documentation"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "chef"

# To develop against a local copy of the chef hugo theme, uncomment this line
# and set the value to the parent directory of where you have checked out the
# chef-hugo-theme repository
# themesDir = "../../../hugo-themes"

pygmentsStyle = "emacs"
pygmentsCodefences = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
    
[[menu.docs]]
name = "Getting started"
weight = 10
identifier = "getting-started"
url = "/docs/getting-started"

[[menu.docs]]
name = "Automate + Builder"
weight = 20
identifier = "builder-automate"
url = "/docs/builder-automate"

[[menu.docs]]
name = "Builder + OAuth"
weight = 30
identifier = "auth"
url = "/docs/auth/"

[[menu.docs]]
name = "Bootstrap Core Packages"
weight = 50
identifier = "bootstrap-core"
url = "/docs/bootstrap-core"

[[menu.docs]]
name = "Example builder.env"
weight = 60
identifier = "builder-example"
url = "/docs/builder-example"

[[menu.docs]]
name = "Postgres"
weight = 70
identifier = "postgres"
url = "/docs/postgres"

[[menu.docs]]
name = "Minio"
weight = 80
identifier = "minio"
url = "/docs/minio"

[[menu.docs]]
name = "Artifactory"
weight = 90
identifier = "artifactory"
url = "/docs/artifactory"

[[menu.docs]]
name = "Troubleshooting"
weight = 100
identifier = "troubleshooting"
url = "/docs/troubleshooting"
